# Generated by Django 5.1 on 2024-08-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievement',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Achievements'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='background_info',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Background Information'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parsed_resume',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Parsed Resume'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_profile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GitHub Username'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=None, help_text='Image size should be png.', null=True, upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
